routes/web.php
        Route::post('/profile',['uses'=>'ProfileController@update_profile','as'=>'update.profile']);
        Route::get('/profile/removePhoto/{id}',['uses'=>'ProfileController@removePhoto','as'=>'removePhoto']);
        Route::get('/password',['uses'=>'ProfileController@change_password','as'=>'change.password']);
        Route::post('/password',['uses'=>'ProfileController@update_password','as'=>'update.password']);
        Route::get('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
});

//Member routes
Route::group(['middleware'=>['auth', 'user'], 'namespace' => 'Member', 'prefix' => 'member', 'as' => 'member.'], function () {
    Route::get('/create/article',['uses'=>'ArticlesController@articles','as'=>'create.article']);
    Route::post('/user/articles',['uses'=>'ArticlesController@saveFile','as'=>'user.add.articles']);
    Route::get('/user/article/history',['uses'=>'ArticlesController@history','as'=>'user.article.history']);
    Route::get('/user/article/read/{id}',['uses'=>'ArticlesController@read','as'=>'user.article.read']);
    Route::get('/user/article/send/{id}',['uses'=>'ArticlesController@send','as'=>'user.article.send']);
    Route::post('/user/article/send/{id}/file',['uses'=>'ArticlesController@send_file','as'=>'user.article.file.send']);
    /*user reviever*/
    Route::get('/user/article/reviewer',['uses'=>'AppController@user_show_articles','as'=>'user.article.reviewer']);
    Route::get('/reviewer/article/meta',['uses'=>'AppController@user_articles_index','as'=>'reviewer.article.meta']);
    Route::post('/admin/reviewer/user/{user_id}/article/{article_meta_id}',['uses'=>'AppController@user_reviewer_ideas','as'=>'reviewer.user.ideas']);
    Route::get('/user/article/reviewer/{id}',['uses'=>'AppController@list_group_item','as'=>'list.group.article.meta']);
    /*user reviever*/

    Route::group(['middleware'=>'user'],function (){

        Route::get('/user',[
            'uses'=>'UserController@getUser',
            'as'=>'get.user'
        ]);

        Route::get('/articles',['uses'=>'UserController@getArticles', 'as'=>'get.articles' ]);
        Route::post('/saveFile',[ 'uses' => 'ArticlesController@saveFile', 'as' => 'saveFile' ]);
        Route::get('/showArticles',['uses'=>'ArticlesController@getShowArticles', 'as'=>'get.show.articles' ]);
        Route::get('/languages',['uses'=>'UserController@getLanguages','as'=>'get.languages']);
    });

    Route::group(['middleware'=>'author'],function(){
        Route::get('/author',['uses'=>'AuthorController@getAuthor', 'as'=>'get.author']);
    });

    Route::group(['middleware'=>'publisher'],function (){
        Route::get('/publisher',[ 'uses'=>'PublisherController@getPublisher',  'as'=>'get.publisher' ]);
        Route::get('/showUserPublisher',['uses'=>'PublisherController@getShowArticlePuslisher', 'as'=>'get.showArticlePuslisher']);
    });
});

//Admin routes
Route::group(['middleware'=>['auth', 'admin']], function () {
    Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
});

Route::group(['middleware'=>['auth', 'admin'],'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function (){
    Route::get('/companies_list',['uses'=>'CompanyController@get_list','as'=>'companies.list']);
    Route::resource('/company','CompanyController');
    Route::get('',['uses'=>'AdminController@getDashboard', 'as'=>'get.admin']);
    Route::get('/articles',['uses'=>'UserArticlesController@index','as'=>'articles.index']);
    Route::get('/articles/list',['uses'=>'UserArticlesController@get_list','as'=>'articles.list']);
    Route::get('/articles/rejected',['uses'=>'UserArticlesController@rejected','as'=>'articles.rejected']);
    Route::get('/articles.rejected.list',['uses'=>'UserArticlesController@rejected_list','as'=>'articles.rejected.list']);
    Route::post('/users/articles/rejected/{id}',['uses'=>'UserArticlesController@article_rejected','as'=>'users.articles.rejected']);
    Route::get('/users/articles/reject/{id}',['uses'=>'UserArticlesController@reject_show','as'=>'reject.show']);
    Route::get('/users/articles/print/{id}',['uses'=>'UserArticlesController@send_print','as'=>'users.articles.print.send']);
    Route::delete('/users/articles/destroy/{id}',['uses'=>'UserArticlesController@destroy','as'=>'articles.destroy']);
    Route::get('/articles/accept',['uses'=>'UserArticlesController@accept_articles','as'=>'accept.articles']);
    Route::get('/articles/accept/list',['uses'=>'UserArticlesController@accept_gel_list','as'=>'articles.accept.list']);
    Route::get('/users/articles/accept/{id}',['uses'=>'UserArticlesController@accept_show','as'=>'article.accept.show']);
    Route::get('/articles/all',['uses'=>'UserArticlesController@all_atricles','as'=>'articles.all']);
    Route::get('/users/articles/all/{id}',['uses'=>'UserArticlesController@all_show','as'=>'articles.all.show']);
    Route::get('/articles/all/list',['uses'=>'UserArticlesController@all_articles_get_list','as'=>'articles.all.list']);
    Route::get('/review/articles/{id}/edit',['uses'=>'ReviewerController@edit','as'=>'reviewer.article.edit']);

    Route::get('/users/articles/{id}',['uses'=>'UserArticlesController@show','as'=>'users.articles']);
    Route::post('/users/articles/destroy/{id}',['uses'=>'UserArticlesController@destroy','as'=>'articles.destroy']);

    // Mobule: Article categories
    Route::get('/categories/removeFile/{id}',['uses'=>'ArticleCategoriesController@removeFile','as'=>'get.remove.file']);
    Route::get('/categories/list', ['uses'=>'ArticleCategoriesController@get_list', 'as'=>'categories.list']);
    Route::resource('/categories', 'ArticleCategoriesController');
    // Mobule: Journal
    Route::get('/journals/list',['uses'=>'JournalsController@get_list','as'=>'journals.list']);
    Route::resource('/journals','JournalsController');
    Route::get('/journal/editions/list',['uses'=>'JournalEditionsController@get_list','as'=>'journal.edition.list']);
    Route::resource('/journal/editions','JournalEditionsController');
    Route::get('/journal/editions/removeFile/{id}',['uses'=>'JournalEditionsController@removeFile','as'=>'get.remove.file']);
    Route::get('/journal/editions/removeDoc/{id}',['uses'=>'JournalEditionsController@removeDoc','as'=>'get.remove.doc']);
    Route::get('/journal/edition/articles/list',['uses'=>'JournalEditionArticlesController@get_list','as'=>'journal.edition.articles.list']);
    Route::resource('/journal/edition/articles','JournalEditionArticlesController');
    Route::get('/journal/edition/articles/removeFile/{id}',['uses'=>'JournalEditionArticlesController@removeFile','as'=>'get.remove.edition.file']);
    Route::get('/journal/edition/articles/removePhoto/{id}',['uses'=>'JournalEditionArticlesController@removePhoto','as'=>'get.remove.edition.photo']);

    /*reviewrs articles*/
    Route::get('/reviewers/index/get/list',['uses'=>'ReviewerController@get_list','as'=>'reviewers.index.get.list']);
    /*reviewers articles*/
    Route::get('/reviewers/index/get/list',['uses'=>'ReviewerController@get_list','as'=>'admin.reviewers.index.get.list']);
    Route::resource('/reviewers','ReviewerController');
    Route::get('/send/revievwer/{id}',['uses'=>'ReviewerController@send','as'=>'send.reviewer']);
    Route::patch('/reviewers/{id}/update',['uses'=>'ReviewerController@patch_update','as'=>'patch.update']);
    /*reviewer articles*/
    /*user reviever*/
    Route::get('/user/article/reviewer',['uses'=>'ReviewerController@user_show_articles','as'=>'user.article.reviewer']);
    Route::get('/reviewer/article/meta',['uses'=>'ReviewerController@user_articles_index','as'=>'reviewer.article.meta']);
    Route::post('/reviewer/user/{user_id}/article/{article_meta_id}',['uses'=>'ReviewerController@user_reviewer_ideas','as'=>'reviewer.user.ideas']);
    /*user reviever*/
    Route::get('/article/meta/info',['uses'=>'ReviewerController@info_index','as'=>'article.info.index']);
    Route::get('/article/meta/info/{id}',['uses'=>'ReviewerController@info_show','as'=>'article.info.show']);
    /*article info*/

    Route::get('admin/info/articles',['uses'=>'ReviewAdminController@info_article','as'=>'info.article']);
    Route::get('/admin/article/info',['ReviewAdminController@get_info','as'=>'get.info']);
    /*article info*/

    //Route::get('/admin/article/meta/info/menu',['uses'=>'ReviewerController@menu','as'=>'menu']);

    Route::get('/journal/edition/articles/list',['uses'=>'JournalEditionArticlesController@get_list','as'=>'journal.edition.articles.list']);
    Route::resource('admin/review/articles','ReviewAdminController');

    Route::resource('journal/categories','ArticleCategories');

    // Module: CMS
    //blog
    Route::group(['prefix' => 'blog', 'as' => 'blog.', 'namespace' => 'Blog'], function () {
        // Categories
        Route::get('categories/list', ['uses'=>'CategoriesController@get_list','as'=>'categories.list']);
        Route::resource('categories', 'CategoriesController');
        // Posts
        Route::get('posts/list', ['uses'=>'PostsController@get_list','as'=>'posts.list']);
        Route::resource('posts', 'PostsController');
        Route::any('posts/upload/{id?}', 'PostsController@upload')->name('posts.upload');
    });
    // pages
    Route::get('/pageslist', ['uses'=>'PagesController@get_list', 'as'=>'pages.list']);
    Route::resource('pages', 'PagesController');
    //menu
    Route::get('menu', array('as' => 'menus', 'uses'=>'MenuController@index'));
    Route::post('/menu/addcustommenu', array('as' => 'menu.addcustommenu', 'uses' => 'MenuController@addcustommenu'));
    Route::post('/menu/deleteitemmenu', array('as' => 'menu.deleteitemmenu', 'uses' => 'MenuController@deleteitemmenu'));
    Route::post('/menu/deletemenug', array('as' => 'menu.deletemenug', 'uses' => 'MenuController@deletemenug'));

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Admin\Companies;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function get_list(Request $request)
    {
        $users = Companies::nodraft()->nodeleted();
        return DataTables::of($users)
            ->addColumn('status', function ($user) {
                if($user->status == 1)
                    return '<span class="label label-success">Актив</span>';
                else
                    return '<span class="label label-danger">Неактив</span>';
            })
            ->addColumn('actions', function ($user) {
                return '
                    <a href="'. url('/admin/company/' . $user->id . '/edit') .'" title="Редактировать"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </button></a>
                    
                    <form method="POST" action="'. url('/admin/company' . '/' . $user->id).'" accept-charset="UTF-8" style="display:inline">
                        '.method_field("DELETE").'
                        '.csrf_field() .'
                        <button type="submit" class="btn btn-danger btn-sm" title="Удалить" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> </button>
                    </form>
                ';
            })
            ->rawColumns(['actions', 'status'])
            ->filter(function ($query) {
                if (request()->filled('status')) {
                    $query->where('status', '=', request('status'));
                }

                if (request()->filled('name')) {
                    $query->where('name', 'like', "%".request('name')."%");
                }

            })
            ->make(true);
    }


    public function index()
    {
        return view('admin.companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = new Companies();
        $company->status = self::STATUS_DRAFT;
        $company->save();

        return redirect('/admin/company/'.$company->id.'/edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Companies::findOrFail($id);
        $isNewRecord = (int)($company->status == Companies::STATUS_DRAFT);

        return view('admin.companies.edit', compact(['company', 'isNewRecord']));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Companies::findorfail($id);

        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required|max:255',
            'ip_address' => 'required',
            'start_date' => 'required',
            'end_date' => 'required'
        ]);

        $requestData = $request->all();

        $company->update($requestData);

        return redirect('/admin/company/' . $company->id . '/edit')->with('success-message', 'Компания успешно редактирована!') ;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Companies::where('id', '=', $id)->update(['is_deleted' => 1]);
        return redirect('admin/company')->with('success-message', 'Компания успешно удалено!');
    }
}

resources/views/admin/companies/edit.blade.php
@extends('layouts.admin')

@section('title')
    @if($isNewRecord) Добавить @else Редактировать @endif
@stop

@section('content')
    <div class="row">
        <form method="POST" action="{{url('/admin/company/'.$company->id)}}" accept-charset="UTF-8" enctype="multipart/form-data">
            {{ method_field('PATCH') }}
            {{ csrf_field() }}
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        @include('includes.messages') @include('includes.error_messages')
                       <div class="row">
                           <div class="col-md-8">
                               <div class="row">
                                   <div class="form-group col-md-12 {{ $errors->has('name') ? 'has-error' : ''}}">
                                       <label for="name" class="control-label">{{ 'Название' }}</label>
                                       <div class="input-group">
                                           <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
                                           <input class="form-control" name="name" type="text" id="name" value="{{ old('Название', $company->name) }}">
                                       </div>
                                       {!! $errors->first('name', '<p class="error-block">:message</p>') !!}
                                   </div>
                                   <div class="form-group col-md-12 {{ $errors->has('description') ? 'has-error' : ''}}">
                                       <textarea name="description" class="form-control">{{ old('description', $company->description) }}</textarea>
                                       {!! $errors->first('description', '<p class="error-block">:message</p>') !!}
                                   </div>

                                   <div class="form-group col-md-12">
                                       <label for="status" class="control-label">{{ 'Статус' }}</label>
                                       <div class="btn-group" data-toggle="buttons">
                                           <label class="btn btn-success btn-rounded {{ (old('status', $company->status) == 1 || $isNewRecord) ? 'active' : '' }} btn-md form-check-label">
                                               <input class="form-check-input" name="status"  value="1" type="radio" {{ (old('status', $company->status) == 1 || $isNewRecord) ? 'checked' : '' }}> Актив
                                           </label>
                                           <label class="btn btn-danger btn-rounded {{ old('status', $company->status) == 0 ? 'active' : '' }} btn-md form-check-label">
                                               <input class="form-check-input" name="status" value="0" type="radio" {{ old('status', $company->status) == 0 ? 'checked' : '' }}> Неактив
                                           </label>
                                       </div>
                                       {!! $errors->first('status', '<p class="error-block">:message</p>') !!}
                                   </div>
                                   <div class="col-md-12">
                                       <div class="form-group">
                                           <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> &nbsp;Сохранить</button>
                                           <a href="{{ url('/admin/journal/editions') }}" title="Back" class="btn btn-default"><span class="fa fa-times-circle"></span> Отменить</a>
                                       </div>
                                   </div>
                               </div>
                           </div>
                           <div class="col-md-4">
                               <div class="row">
                                   <div class="form-group col-md-12" style="margin-top: 5px;">
                                       <br>
                                       <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> &nbsp;Сохранить</button>
                                       <a href="{{ url('/admin/company') }}" title="Back" class="btn btn-default"><span class="fa fa-times-circle"></span> Отменить</a>
                                   </div>
                                   <div class="form-group col-md-12 {{ $errors->has('ip_address') ? 'has-error' : ''}}">
                                       <label for="ip_address" class="control-label">{{ 'IP-адрес' }}</label>
                                       <div class="input-group">
                                           <div class="input-group-addon"><i class="fa fa-barcode"></i></div>
                                           <input type="text" id="ip_address" class="form-control" name="ip_address" value="{{ old('ip_address', $company->ip_address) }}" >
                                       </div>
                                       {!! $errors->first('start_date', '<p class="error-block">:message</p>') !!}
                                   </div>

                                   <div class="form-group col-md-12 {{ $errors->has('start_date') ? 'has-error' : ''}}">
                                       <label for="date_edition" class="control-label">{{ 'Дата начала' }}</label>
                                       <div class="input-group">
                                           <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                                           <input type="text" id="start_date" class="form-control datepicker" name="start_date" value="{{ old('start_date', $company->start_date) }}" >
                                       </div>
                                       {!! $errors->first('start_date', '<p class="error-block">:message</p>') !!}
                                   </div>

                                   <div class="form-group col-md-12 {{ $errors->has('end_date') ? 'has-error' : ''}}">
                                       <label for="date_edition" class="control-label">{{ 'Дата окончания' }}</label>
                                       <div class="input-group">
                                           <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                                           <input type="text" id="end_date" class="form-control datepicker" name="end_date" value="{{ old('end_date', $company->end_date) }}" >
                                       </div>
                                       {!! $errors->first('end_date', '<p class="error-block">:message</p>') !!}
                                   </div>
                               </div>
                           </div>
                       </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

@section('scripts')
    <script src="//cdn.ckeditor.com/4.6.2/full-all/ckeditor.js"></script>
    <script src="{{asset('backend/js/ckeditor_options')}}"></script>
    <script src="{{ asset('/backend/js/ckeditor_options.js') }}"></script>
    <script>
        CKEDITOR.replace('description', options);
    </script>
@stop

resources/views/admin/companies/index.blade.php
@extends('layouts.admin')

@section('title')
    Компания
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <a href="{{ url('/admin/company/create') }}" class="btn btn-success pull-right">
                        <i class="fa fa-plus" aria-hidden="true"></i> Создать
                    </a>
                </div>

                @include('includes.messages') @include('includes.error_messages')
                <div class="box-body">
                    <div class="search-box">
                        <form method="POST" id="search-form" class="form-inline" role="form">
                            <div class="form-group">
                                <select  class="form-control"  name="status">
                                    <option value=""></option>
                                    <option value="1">Актив</option>
                                    <option value="0">Неактив</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="name" id="name" placeholder="Название">
                            </div>
                            <button type="submit" class="btn btn-primary">Поиск</button>
                        </form>
                    </div>

                    <br>

                    <div class="table-responsive">
                        <table class="table table-bordered" id="users-table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Статус</th>
                                    <th>Название</th>
                                    <th>IP-адрес</th>
                                    <th>Дата начала</th>
                                    <th>Дата окончания</th>
                                    <th>Действие</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>

@section('scripts')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var oTable = $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            bLengthChange: false,
            bFilter: false,
            ajax: {
                url: "{{  route('admin.companies.list') }}",
                method: 'GET',
                data: function (d) {
                    var filter_data = $('#search-form').serializeArray();
                    $.each(filter_data, function(key, item) {
                        d[item.name] = item.value;
                    });
                }
            },
            columns: [
                {data: 'id', name: 'id'},
                {data: 'status', name: 'status'},
                {data: 'name', name: 'name'},
                {data:'ip_address',name:'ip_address'},
                {data: 'start_date', name: 'start_date'},
                {data: 'end_date',name:'end_date'},
                {data: 'actions', name: 'actions', orderable: false}
            ]
        });

        $('#search-form').on('submit', function(e) {
            oTable.draw();
            e.preventDefault();
        });
    </script>
@stop

@endsection

resources/views/admin/companies/show.blade.php
@extends('layouts.admin')

@section('title')
   User
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <a href="{{ url('/admin/users') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                    <a href="{{ url('/admin/admins/' . $admin->id . '/edit') }}" title="Edit Models\Admin"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                    <form method="POST" action="{{ url('admin/admins' . '/' . $admin->id) }}" accept-charset="UTF-8" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-danger btn-sm" title="Delete Admin" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                    </form>
                </div>

                @if(\Session::has('success'))
                    <div class="alert alert-success">
                        {{\Session::get('success')}}
                    </div>
                @endif
                <div class="box-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $admin->id }}</td>
                                    </tr>
                                    <tr><th> Fio </th><td> {{ $admin->fio }} </td></tr><tr><th> Email </th><td> {{ $admin->email }} </td></tr><tr><th> Role Id </th><td> {{ $admin->role_id }} </td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection