routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' =>LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function() {
    //Main
    Route::get('/',['uses'=>'AppController@index', 'as'=>'index']);
    Route::get('publish',['uses'=>'Site\PublishController@index', 'as'=>'publish']);
    Route::get('page/{id}',['uses'=>'Site\PageController@index', 'as'=>'page']);

    Route::get('news', ['uses'=>'Site\NewsController@index', 'as'=>'news']);
    Route::get('news/{id}', 'Site\NewsController@view');

    Route::get('categories', ['uses'=>'Site\CategoriesController@index', 'as'=>'categories']);

    Route::get('archive',['uses'=>'Site\ArchiveController@index', 'as'=>'archive']);
    Route::get('archive/{id}', 'Site\ArchiveController@view');

    Route::get('articles', ['uses'=>'Site\ArticlesController@index', 'as'=>'articles']);
    Route::get('articles/{id}', 'Site\ArticlesController@view');

    Route::get('events', ['uses'=>'Site\EventsController@index', 'as'=>'events']);
    Route::get('events/{id}', 'Site\EventsController@view');

    Route::get('search', 'Site\SearchController@index');

    //Auth Routes
    Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
        Route::group(['middleware' => 'guest'], function () {
            //Login
            Route::get('/login', ['uses' => 'LoginController@showLogin', 'as' => 'login']);
            Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'post.login']);

            //Registration
            Route::get('registration', ['uses' => 'RegisterController@showRegistration', 'as' => 'registration']);
            Route::post('registration', ['uses' => 'RegisterController@register', 'as' => 'post.registration']);

            // Confirmation Routes...
            Route::get('confirm/{token}', 'RegisterController@confirm')->name('confirm');

            // Password Reset Routes...
            Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
            Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
            Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
            Route::post('password/reset', 'ResetPasswordController@reset');
        });

        Route::get('/profile',['uses'=>'ProfileController@profile','as'=>'profile']);
        Route::post('/profile',['uses'=>'ProfileController@update_profile','as'=>'update.profile']);
        Route::get('/profile/removePhoto/{id}',['uses'=>'ProfileController@removePhoto','as'=>'removePhoto']);
        Route::get('/password',['uses'=>'ProfileController@change_password','as'=>'change.password']);
        Route::post('/password',['uses'=>'ProfileController@update_password','as'=>'update.password']);
        Route::get('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
});

//Member routes
Route::group(['middleware'=>['auth', 'user'], 'namespace' => 'Member', 'prefix' => 'member', 'as' => 'member.'], function () {
    Route::get('/create/article',['uses'=>'ArticlesController@articles','as'=>'create.article']);
    Route::post('/user/articles',['uses'=>'ArticlesController@saveFile','as'=>'user.add.articles']);
    Route::get('/user/article/history',['uses'=>'ArticlesController@history','as'=>'user.article.history']);
    Route::get('/user/article/read/{id}',['uses'=>'ArticlesController@read','as'=>'user.article.read']);
    Route::get('/user/article/send/{id}',['uses'=>'ArticlesController@send','as'=>'user.article.send']);
    Route::post('/user/article/send/{id}/file',['uses'=>'ArticlesController@send_file','as'=>'user.article.file.send']);
    /*user reviever*/
    Route::get('/user/article/reviewer',['uses'=>'AppController@user_show_articles','as'=>'user.article.reviewer']);
    Route::get('/reviewer/article/meta',['uses'=>'AppController@user_articles_index','as'=>'reviewer.article.meta']);
    Route::post('/admin/reviewer/user/{user_id}/article/{article_meta_id}',['uses'=>'AppController@user_reviewer_ideas','as'=>'reviewer.user.ideas']);
    Route::get('/user/article/reviewer/{id}',['uses'=>'AppController@list_group_item','as'=>'list.group.article.meta']);
    /*user reviever*/

    Route::group(['middleware'=>'user'],function (){

        Route::get('/user',[
            'uses'=>'UserController@getUser',
            'as'=>'get.user'
        ]);

        Route::get('/articles',['uses'=>'UserController@getArticles', 'as'=>'get.articles' ]);
        Route::post('/saveFile',[ 'uses' => 'ArticlesController@saveFile', 'as' => 'saveFile' ]);
        Route::get('/showArticles',['uses'=>'ArticlesController@getShowArticles', 'as'=>'get.show.articles' ]);
        Route::get('/languages',['uses'=>'UserController@getLanguages','as'=>'get.languages']);
    });

    Route::group(['middleware'=>'author'],function(){
        Route::get('/author',['uses'=>'AuthorController@getAuthor', 'as'=>'get.author']);
    });

    Route::group(['middleware'=>'publisher'],function (){
        Route::get('/publisher',[ 'uses'=>'PublisherController@getPublisher',  'as'=>'get.publisher' ]);
        Route::get('/showUserPublisher',['uses'=>'PublisherController@getShowArticlePuslisher', 'as'=>'get.showArticlePuslisher']);
    });
});

//Admin routes
Route::group(['middleware'=>['auth', 'admin']], function () {
    Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
});

Route::group(['middleware'=>['auth', 'admin'],'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function (){
    Route::get('/companies_list',['uses'=>'CompanyController@get_list','as'=>'companies.list']);
    Route::resource('/company','CompanyController');
    Route::get('',['uses'=>'AdminController@getDashboard', 'as'=>'get.admin']);
    Route::get('/articles',['uses'=>'UserArticlesController@index','as'=>'articles.index']);
    Route::get('/articles/list',['uses'=>'UserArticlesController@get_list','as'=>'articles.list']);
    Route::get('/articles/rejected',['uses'=>'UserArticlesController@rejected','as'=>'articles.rejected']);
    Route::get('/articles.rejected.list',['uses'=>'UserArticlesController@rejected_list','as'=>'articles.rejected.list']);
    Route::post('/users/articles/rejected/{id}',['uses'=>'UserArticlesController@article_rejected','as'=>'users.articles.rejected']);
    Route::get('/users/articles/reject/{id}',['uses'=>'UserArticlesController@reject_show','as'=>'reject.show']);
    Route::get('/users/articles/print/{id}',['uses'=>'UserArticlesController@send_print','as'=>'users.articles.print.send']);
    Route::delete('/users/articles/destroy/{id}',['uses'=>'UserArticlesController@destroy','as'=>'articles.destroy']);
    Route::get('/articles/accept',['uses'=>'UserArticlesController@accept_articles','as'=>'accept.articles']);
    Route::get('/articles/accept/list',['uses'=>'UserArticlesController@accept_gel_list','as'=>'articles.accept.list']);
    Route::get('/users/articles/accept/{id}',['uses'=>'UserArticlesController@accept_show','as'=>'article.accept.show']);
    Route::get('/articles/all',['uses'=>'UserArticlesController@all_atricles','as'=>'articles.all']);
    Route::get('/users/articles/all/{id}',['uses'=>'UserArticlesController@all_show','as'=>'articles.all.show']);
    Route::get('/articles/all/list',['uses'=>'UserArticlesController@all_articles_get_list','as'=>'articles.all.list']);
    Route::get('/review/articles/{id}/edit',['uses'=>'ReviewerController@edit','as'=>'reviewer.article.edit']);

    Route::get('/users/articles/{id}',['uses'=>'UserArticlesController@show','as'=>'users.articles']);
    Route::post('/users/articles/destroy/{id}',['uses'=>'UserArticlesController@destroy','as'=>'articles.destroy']);

    // Mobule: Article categories
    Route::get('/categories/removeFile/{id}',['uses'=>'ArticleCategoriesController@removeFile','as'=>'get.remove.file']);
    Route::get('/categories/list', ['uses'=>'ArticleCategoriesController@get_list', 'as'=>'categories.list']);
    Route::resource('/categories', 'ArticleCategoriesController');
    // Mobule: Journal
    Route::get('/journals/list',['uses'=>'JournalsController@get_list','as'=>'journals.list']);
    Route::resource('/journals','JournalsController');
    Route::get('/journal/editions/list',['uses'=>'JournalEditionsController@get_list','as'=>'journal.edition.list']);
    Route::resource('/journal/editions','JournalEditionsController');
    Route::get('/journal/editions/removeFile/{id}',['uses'=>'JournalEditionsController@removeFile','as'=>'get.remove.file']);
    Route::get('/journal/editions/removeDoc/{id}',['uses'=>'JournalEditionsController@removeDoc','as'=>'get.remove.doc']);
    Route::get('/journal/edition/articles/list',['uses'=>'JournalEditionArticlesController@get_list','as'=>'journal.edition.articles.list']);
    Route::resource('/journal/edition/articles','JournalEditionArticlesController');
    Route::get('/journal/edition/articles/removeFile/{id}',['uses'=>'JournalEditionArticlesController@removeFile','as'=>'get.remove.edition.file']);
    Route::get('/journal/edition/articles/removePhoto/{id}',['uses'=>'JournalEditionArticlesController@removePhoto','as'=>'get.remove.edition.photo']);

    /*reviewrs articles*/
    Route::get('/reviewers/index/get/list',['uses'=>'ReviewerController@get_list','as'=>'reviewers.index.get.list']);
    /*reviewers articles*/

app/Http/Controllers/Admin/Blog/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Models\Article_Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Admin\Blog\Categories;
use Illuminate\Support\Facades\URL;
use Yajra\Datatables\Datatables;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.blog.categories.index');
    }

    public function get_list(Request $request)
    {
        $categories = Categories::active();

        return Datatables::of($categories)
            ->addColumn('image',function ($image){
                return "<img src='".URL::to('/img1/')."/article.jpg"."'>";
            })
            ->addColumn('actions', function ($category) {
                return '
                    <a href="'. url('/admin/blog/categories/' . $category->id . '/edit') .'" title="Редактировать"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </button></a>
                ';
            })
            ->rawColumns(['actions'])
            ->filter(function ($query) {
                if (request()->filled('slug')) {
                    $query->where('slug', 'like', "%".request('slug')."%");
                }
            })
            ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Categories();
        $category->status = self::STATUS_DRAFT;
        $category->save();
        return redirect('admin/blog/categories/'.$category->id.'/edit');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Categories::findorfail($id);
        $isNewRecord = (int)($category->status == self::STATUS_DRAFT);
        return view('admin.blog.categories.edit', compact(['category','isNewRecord']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'slug' => 'required|max:255',
            'name_ru'=>'required',
            'name_en'=>'required'
        ]);
        $category = Categories::findorfail($id);
        $category->status = self::STATUS_ACTIVE;
        $category->slug = $request->slug;
        $category->name_ru = $request->name_ru;
        $category->name_en = $request->name_en;
        $category->save();
        return redirect('/admin/blog/categories/' . $category->id . '/edit')->with('success-message', 'Thanks!') ;

    }
}

app/Http/Controllers/Site/CategoriesController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Models\Site\ArticleCategories;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function index(Request $request)
    {
        $categories = ArticleCategories::active()->paginate(12);
        return view('site.categories.index', ['categories'=>$categories]);
    }
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title')
    @if($isNewRecord) Создать рубкика @else Редактировать рубрика @endif
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    @include('includes.messages') @include('includes.error_messages')
                    <form method="POST" action="{{ url('/admin/categories/'.$category->id) }}" accept-charset="UTF-8" enctype="multipart/form-data">
                        {{ method_field('PATCH') }}
                        {{ csrf_field() }}

                        <div class="form-group col-md-12">
                            <label for=""></label>
                            <div class="nav-tabs-custom">
                                <ul class="nav nav-tabs">
                                    <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="false" style="{{ $errors->has('name_ru') ? 'color:#a94442;' : ''}}" >Русские</a></li>
                                    <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="true" style="{{ $errors->has('name_ru') ? 'color:#a94442;' : ''}}">English</a></li>
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane active" id="tab_1">
                                        <div class="{{ $errors->has('name_ru') ? 'has-error' : ''}}">
                                            <label for="name_ru" class="control-label required">{{ 'Загаловок' }}</label>
                                            <input class="form-control" name="name_ru" type="text" id="name_ru" value="{{ $category->name_ru or ''}}">
                                            {!! $errors->first('name_ru', '<p class="error-block">:message</p>') !!}
                                        </div>
                                        <div class="tab-pane active" id="tab_3">
                                            <div class="{{ $errors->has('description_ru') ? 'has-error' : ''}}">
                                                <label for="description_ru" class="control-label required">{{ 'Oписание' }}</label>
                                                <textarea name="description_ru" id="description_ru" cols="30" class="form-control" placeholder="Название" rows="10">{{ $category->description_ru }}</textarea>
                                                {!! $errors->first('description_ru', '<p class="error-block">:message</p>') !!}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="tab_2">
                                        <div class="{{ $errors->has('name_en') ? 'has-error' : ''}}">
                                            <label for="name_en" class="control-label required">{{ 'Title' }}</label>
                                            <input class="form-control" name="name_en" type="text" id="name_en" value="{{ $category->name_en or ''}}">
                                            {!! $errors->first('name_en', '<p class="error-block">:message</p>') !!}
                                        </div>
                                        <div class="tab-pane" id="tab_4">
                                            <div class="{{ $errors->has('description_en') ? 'has-error' : ''}}">
                                                <label for="description_en" class="control-label required">{{ 'Description' }}</label>
                                                <textarea name="description_en" id="description_en" class="form-control" cols="30" rows="10">{{ $category->description_en }}</textarea>
                                                {!! $errors->first('description_en', '<p class="error-block">:message</p>') !!}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <label for="photo" class="control-label">{{ 'Фото' }}</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-id-card-o"></i></div>
                                <input class="form-control" name="photo" type="file" id="photo">
                            </div>
                            <div class="img-input-show">
                                @if($category->photo)
                                    <img src="{{ App\Libraries\UploadManager::getPhoto('categories', $category->id, 'original', $category->photo)}}" class="img-thumbnail" width="150"/>
                                    <a href="{{ url('/admin/categories/removeFile/'.$category->id) }}" >удалить фото</a>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> &nbsp;Сохранить</button>
                                <a href="{{ url('/admin/categories') }}" title="Back" class="btn btn-default"><span class="fa fa-times-circle"></span> Отменить</a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('title') Категории @stop
@section('title-child') рубрики @stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <a href="{{ url('/admin/categories/create') }}" class="btn btn-success pull-right">
                        <i class="fa fa-plus" aria-hidden="true"></i> Добавить
                    </a>
                </div>

                @include('includes.messages') @include('includes.error_messages')
                <div class="box-body">
                    <div class="search-box">
                        <form method="POST" id="search-form" class="form-inline" role="form">
                            <div class="form-group">
                                <input type="text" class="form-control" name="name_ru" id="name_ru" placeholder="Название">
                            </div>
                            <button type="submit" class="btn btn-primary">Поиск</button>
                        </form>
                    </div>

                    <br>

                    <div class="table-responsive">
                        <table class="table" id="users-table">
                            <thead>
                            <tr>
                                <th>Загаловок</th>
                                <th width="10%">Действие</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
@endsection

@section('scripts')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var oTable = $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            bLengthChange: false,
            bFilter: false,
            ajax: {
                url: "{{  route('admin.categories.list') }}",
                method: 'GET',
                data: function (d) {
                    var filter_data = $('#search-form').serializeArray();
                    $.each(filter_data, function(key, item) {
                        d[item.name] = item.value;
                    });
                }
            },
            columns: [
                {data:'name_ru',name:'name_ru'},
                {data: 'actions', name: 'actions', orderable: false}
            ]
        });

        $('#search-form').on('submit', function(e) {
            oTable.draw();
            e.preventDefault();
        });
    </script>
@stop

resources/views/admin/categories/show.blade.php
@extends('layouts.admin')

@section('title')
    Administrator
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <a href="{{ url('/admin/categories') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                    <a href="{{ url('/admin/categories/' . $category->id . '/edit') }}" title="Edit Admin"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                    <form method="POST" action="{{ url('admin/categories' . '/' . $category->id) }}" accept-charset="UTF-8" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-danger btn-sm" title="Delete Admin" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                    </form>
                </div>

                @if(\Session::has('success'))
                    <div class="alert alert-success">
                        {{\Session::get('success')}}
                    </div>
                @endif
                <div class="box-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $category->id }}</td>
                                    </tr>
                                    <tr>
                                        <th> Name </th><td> {{ $category->name }} </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection